name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Auto-increment Patch Version
      run: |
        # Extract the current version from pom.xml
        CURRENT_VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
        echo "Current Version: $CURRENT_VERSION"
        
        # Increment the patch version
        NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$NF++;print}')
        echo "New Version: $NEW_VERSION"
        
        # Update pom.xml with the new version
        sed -i "s/<version>$CURRENT_VERSION<\/version>/<version>$NEW_VERSION<\/version>/" pom.xml
    

    - name: Build with Maven
      run: mvn -B package --file myapp/pom.xml

    
